version: 2
jobs:
  deploy:
    steps:
      - run:
          name: Push to S3
          command: | 
            s3_website cfg apply
            s3_website push
workflows:
  version: 2
  build_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master